### ISSUE TITLE
Could not find file '/usr/share/zoneinfo/Canada/East-Saskatchewan'.

### ISSUE THREAD

**Issue by lusgon** [mj1856/TimeZoneConverter#71]
I am using **microsoft mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim** image for hosting a **.NET Core 3.1** web API application on **Docker**. When I use the method `TZConvert.GetTimeZoneInfo("E. South America Standard Time")` of the **3.2.0 TimeZoneConverter nuget pack** I get a exception on `TZConvert.GetSystemTimeZones()` who kills my container even as the nuget pack TimeZoneConverter method call that throws the exception to me `TimeZoneInfo.FindSystemTimeZoneById("Canada/Saskatchewan");` is inside a try catch block. 

The exceptions details are the following:
```
System.IO.FileNotFoundException
  HResult=0x80070002
  Message=Could not find file '/usr/share/zoneinfo/Canada/East-Saskatchewan'.
  Source=System.Private.CoreLib
  StackTrace:
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)


System.TimeZoneNotFoundException
  HResult=0x80131500
  Message=The time zone ID 'Canada/East-Saskatchewan' was not found on the local computer.
  Source=System.Private.CoreLib
  StackTrace:
   at System.TimeZoneInfo.FindSystemTimeZoneById(String id)

Inner Exception 1:
FileNotFoundException: Could not find file '/usr/share/zoneinfo/Canada/East-Saskatchewan'.
```
Regards

**Comment by lusgon** [comment]
The error that killer the server was mine.
